name: list_twolevel_demo
description: A simple two level listbuilder fill with Map<> Obj.
version: 1.0.0+1
homepage: https://github.com/shAdow-XJY/list_twolevel
environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  list_twolevel:
    path: ../

flutter:

  uses-material-design: true
  assets:
    - assets/

